Support for comparing objects with boolean type in `isLike` function
lambdalisue/deno-unknownutil pull request #2
Opened 2021-07-20 12:31 UTC by monaqa

Added the ability to compare objects/arrays containing bool types with isLike.

To achieve this, I have added two functions and their corresponding tests.

- `isBoolean(x: unknown): x is boolean` : returns true if and only if `x` is boolean
- `ensureBoolean(x: unknown): asserts x is boolean` : ensures `x` is boolean

2021-07-20 12:41 UTC, lambdalisue requested changes
Additionally, please add entries to `README.md`

2021-07-20 12:41 UTC, lambdalisue commented on is_test.ts
> +
Please add tests like the below to all other tests.

```typescript
assertEquals(isXXXXX(true), false);
assertEquals(isXXXXX(true), false);
```

2021-07-20 12:41 UTC, lambdalisue commented on ensure_test.ts
> +});
Please add tests like the below to all other tests

```typescript
assertThrows(() => ensureXXX(true));
assertThrows(() => ensureXXX(false));
```

2021-07-20 12:41 UTC, lambdalisue commented on is_test.ts
> +});
Please add the below to other tests

```typescript
assertEquals(isLike(ref, true), false);
assertEquals(isLike(ref, false), false);
```

2021-07-20 16:18 UTC, lambdalisue approved these changes
LGTM

2021-07-20 16:19 UTC, lambdalisue requested changes
Please fix CI error

2021-07-21 01:23 UTC, lambdalisue commented
Additionally, please click "Re-request review" so that I can notice changes. @monaqa 

![CleanShot 2021-07-21 at 10 22 29](https://user-images.githubusercontent.com/546312/126415689-85cce1a4-b18e-4fbb-bb0c-2c0b440119b6.png)

2021-07-22 13:33 UTC, monaqa commented
Thank you for your review, and sorry, I forgot to run `deno fmt`.

2021-07-22 16:23 UTC, lambdalisue approved these changes

2021-07-22 16:23 UTC, merged